stages:
  - build
  - test
  - deploy

build_development:
  stage: build
  only:
    - develop
  tags:
    - build
  cache:
    paths:
      - node_modules/
  before_script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - nvm install 12.20.0
  script:
    - npm install
    - npm run build-dev
  artifacts:
    paths:
      - dist/
  
deploy_development:
  stage: deploy
  dependencies:
    - build_development
  only:
    - develop
  tags:
    - deploy
  script:
    - rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" dist/ ubuntu@alloo.cc:~/app/blanc

# build_development:
#   stage: build
#   only:
#     - develop
#   tags:
#     - build
#   cache:
#     paths:
#       - node_modules/
#   before_script:
#     - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
#     - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
#     - nvm install 12.20.0
#   script:
#     - npm install
#     - node ace build --production
#     - cp .env.development build/.env
#     - cd build
#     - npm install
#   artifacts:
#     paths:
#       - build/

# deploy_development:
#   stage: deploy
#   dependencies:
#     - build_development
#   only:
#     - develop
#   tags:
#     - deploy
#   script:
#     - ssh -o StrictHostKeyChecking=no ubuntu@172.31.35.141 'rm -rf ~/app/blanc'
#     - scp -r ./build ubuntu@172.31.35.141:~/app/blanc
#     - ssh ubuntu@172.31.35.141 'bash -ic "cd ~/app/blanc; pm2 start ecosystem.config.js"'
